name: Hello World
on: workflow_dispatch
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo "This is line one"
          echo "This is line two"
          echo "This is line three"
