name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "A build demo"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: echo "A test demo"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy step
        run: echo "A deploy demo"
     

