name: Outputs Demo
on: push
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
       - name: Step-on
         id: step1
         run: echo "version=0.0.1" >> $GITHUB_OUTPUT
       - name: Step-two
         run: echo "This version is ${{ steps.step1.outputs.version }}"
